<a href="https://colab.research.google.com/github/saim9211/DeepLearning/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [28]:
# Import torch

import torch
# Create random tensor
tensor_1=torch.rand(7,7)
print(tensor_1.shape)



torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
tensor_2=torch.rand(1,7)
print(tensor_1.shape,"shape of other",tensor_2.shape,"shape of other")
print(torch.matmul(tensor_1,tensor_2.T))

# Perform matrix multiplication


torch.Size([7, 7]) shape of other torch.Size([1, 7]) shape of other
tensor([[2.1713],
        [1.0949],
        [2.9806],
        [1.6932],
        [2.0622],
        [2.4584],
        [2.1789]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
import torch
seed=0

# Create two random tensors
torch.manual_seed(seed)
tensor_1=torch.rand(7,7)
torch.manual_seed(seed)
tensor_2=torch.rand(1,7)


# Matrix multiply tensors
print(torch.matmul(tensor_1,tensor_2.T))


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
seed =1234
torch.manual_seed(seed)
tensor_1=torch.rand(7,7)
torch.manual_seed(seed)
tensor_2=torch.rand(1,7)
print(torch.matmul(tensor_1,tensor_2.T))



tensor([[0.8613],
        [1.2761],
        [1.1540],
        [1.0134],
        [0.6783],
        [1.1122],
        [0.7266]])



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [16]:
# Set random seed
torch.manual_seed(1234)


# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_1=torch.rand(2,3).to(device)
tensor_2=torch.rand(2,3).to(device)
print(tensor_1,tensor_2)
print(tensor_1.shape,tensor_2.shape)
print(tensor_2.T.shape)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')
torch.Size([2, 3]) torch.Size([2, 3])
torch.Size([3, 2])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [17]:
# Perform matmul on tensor_A and tensor_B
mul=torch.matmul(tensor_1,tensor_2.T)
print(mul,mul.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [19]:
# Find max
print(torch.max(mul))

# Find min
print(torch.min(mul))

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max

torch.argmax(mul)
# Find arg min
torch.argmin(mul)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [27]:
# Set seed
seed=7


# Create random tensor
torch.manual_seed(seed)
tensor=torch.rand(1,1,1,10)
print(tensor,tensor.shape)
# Remove single dimensions
squeez_tensor=tensor.squeeze()
# Print out tensors and their shapes
print(squeez_tensor,squeez_tensor.shape)





tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
