<a href="https://colab.research.google.com/github/saim9211/DeepLearning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### resource to follow  : https://www.learnpytorch.io/00_pytorch_fundamentals/


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import torch
print(torch.__version__)

2.11.0+cpu


### introduction to tensor in detial

In [2]:
scalar=torch.tensor(6)
scalar

tensor(6)

In [3]:
scalar.ndim

0

In [9]:
# getting back the tensor as number
scalar.item()

6

In [31]:
# vector number
vec=torch.tensor([4,3])

In [32]:
# vector dimension
# trick count the number of square brackets outside of one side

vec.ndim

1

In [33]:
# tell about the element inside and  the outside
vec.shape

torch.Size([2])

In [17]:
# matrix
matrix=torch.tensor([[1,2,3],[4,5,6]])
print(matrix.ndim)
#number of row and column
print(matrix.shape)
print(matrix[1])

2
torch.Size([2, 3])
tensor([4, 5, 6])


In [25]:
# practice

matrix=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


#### for random tensor creation bcz most of the machine learning used the random tensor  first creat the random tensor and then according to data update it optimize them
start with the random number -> look at the data-> update the random tensor -> look at the data -> update random tensor


In [38]:
ran_Tensor=torch.rand(3,4)
print(ran_Tensor)
print(ran_Tensor.ndim)
print(ran_Tensor.shape)
# to get the type of the tensor
print(ran_Tensor.dtype)

tensor([[0.5693, 0.8597, 0.8858, 0.2331],
        [0.3694, 0.5481, 0.8424, 0.2083],
        [0.2155, 0.0934, 0.7012, 0.0491]])
2
torch.Size([3, 4])
torch.float32


In [59]:
# it can adjust the size to be whatever we want
# it means 4 rows and 4 column 2 dimesional one matrix
torch.random=torch.rand(size=(4,4))
# it means 4 sample of 4 rows and 2 column
torch.random=torch.rand(size=(4,4,2))
# it means 2  sample(  (4sample(4,2))
# (2 batch size  (((4 channel  (4 rows,2  column))))
random_tensor=torch.rand(size=(2,4,4,2))
print(random_tensor.shape)
print("dimension:",random_tensor.ndim)
print(random_tensor)

torch.Size([2, 4, 4, 2])
dimension: 4
tensor([[[[0.0671, 0.5664],
          [0.3048, 0.8619],
          [0.4842, 0.7972],
          [0.3956, 0.7203]],

         [[0.6811, 0.2032],
          [0.4973, 0.7171],
          [0.3267, 0.9850],
          [0.9980, 0.9958]],

         [[0.4840, 0.4159],
          [0.9415, 0.1100],
          [0.7320, 0.1540],
          [0.2941, 0.8074]],

         [[0.4260, 0.6533],
          [0.1962, 0.0359],
          [0.2623, 0.9599],
          [0.2573, 0.8376]]],


        [[[0.5302, 0.0709],
          [0.7398, 0.0174],
          [0.8214, 0.8608],
          [0.6643, 0.4417]],

         [[0.4637, 0.4280],
          [0.0061, 0.4753],
          [0.1048, 0.9214],
          [0.0023, 0.2402]],

         [[0.5913, 0.8704],
          [0.4764, 0.0920],
          [0.2580, 0.2977],
          [0.1257, 0.7874]],

         [[0.3534, 0.0535],
          [0.8102, 0.7902],
          [0.1044, 0.8073],
          [0.5503, 0.1668]]]])
