<a href="https://colab.research.google.com/github/saim9211/DeepLearning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### resource to follow  : https://www.learnpytorch.io/00_pytorch_fundamentals/


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import torch
print(torch.__version__)

2.11.0+cpu


### introduction to tensor in detial

In [2]:
scalar=torch.tensor(6)
scalar

tensor(6)

In [3]:
scalar.ndim

0

In [9]:
# getting back the tensor as number
scalar.item()

6

In [31]:
# vector number
vec=torch.tensor([4,3])

In [32]:
# vector dimension
# trick count the number of square brackets outside of one side

vec.ndim

1

In [33]:
# tell about the element inside and  the outside
vec.shape

torch.Size([2])

In [17]:
# matrix
matrix=torch.tensor([[1,2,3],[4,5,6]])
print(matrix.ndim)
#number of row and column
print(matrix.shape)
print(matrix[1])

2
torch.Size([2, 3])
tensor([4, 5, 6])


In [25]:
# practice

matrix=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


#### for random tensor creation bcz most of the machine learning used the random tensor  first creat the random tensor and then according to data update it optimize them
start with the random number -> look at the data-> update the random tensor -> look at the data -> update random tensor


In [38]:
ran_Tensor=torch.rand(3,4)
print(ran_Tensor)
print(ran_Tensor.ndim)
print(ran_Tensor.shape)
# to get the type of the tensor
print(ran_Tensor.dtype)

tensor([[0.5693, 0.8597, 0.8858, 0.2331],
        [0.3694, 0.5481, 0.8424, 0.2083],
        [0.2155, 0.0934, 0.7012, 0.0491]])
2
torch.Size([3, 4])
torch.float32


In [59]:
# it can adjust the size to be whatever we want
# it means 4 rows and 4 column 2 dimesional one matrix
torch.random=torch.rand(size=(4,4))
# it means 4 sample of 4 rows and 2 column
torch.random=torch.rand(size=(4,4,2))
# it means 2  sample(  (4sample(4,2))
# (2 batch size  (((4 channel  (4 rows,2  column))))
random_tensor=torch.rand(size=(2,4,4,2))
print(random_tensor.shape)
print("dimension:",random_tensor.ndim)
print(random_tensor)

torch.Size([2, 4, 4, 2])
dimension: 4
tensor([[[[0.0671, 0.5664],
          [0.3048, 0.8619],
          [0.4842, 0.7972],
          [0.3956, 0.7203]],

         [[0.6811, 0.2032],
          [0.4973, 0.7171],
          [0.3267, 0.9850],
          [0.9980, 0.9958]],

         [[0.4840, 0.4159],
          [0.9415, 0.1100],
          [0.7320, 0.1540],
          [0.2941, 0.8074]],

         [[0.4260, 0.6533],
          [0.1962, 0.0359],
          [0.2623, 0.9599],
          [0.2573, 0.8376]]],


        [[[0.5302, 0.0709],
          [0.7398, 0.0174],
          [0.8214, 0.8608],
          [0.6643, 0.4417]],

         [[0.4637, 0.4280],
          [0.0061, 0.4753],
          [0.1048, 0.9214],
          [0.0023, 0.2402]],

         [[0.5913, 0.8704],
          [0.4764, 0.0920],
          [0.2580, 0.2977],
          [0.1257, 0.7874]],

         [[0.3534, 0.0535],
          [0.8102, 0.7902],
          [0.1044, 0.8073],
          [0.5503, 0.1668]]]])


Zeros  and ones

In [63]:
# create the tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [64]:
# create the ones tensor
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

concept of the range

In [70]:
# it work like the same like numpy np.arange
print(torch.arange(1,10))
# start ,end, then steps in them
print(torch.arange(start=0,end=1000,step=100))


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])


In [76]:
one_to_fiver=torch.arange(start=1,end=6,step=1)
print(one_to_fiver)
# make the use of the _like method to make it change like other
zero_one_fiver=torch.zeros_like(input=one_to_fiver)
print(zero_one_fiver)
one=torch.ones_like(input=one_to_fiver)
print(one)

tensor([1, 2, 3, 4, 5])
tensor([0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1])


In [102]:
tensor=torch.tensor([[1,2,3],[4,5,6]])
print(tensor)
print(tensor[1])
# for changing the certain vector in the tensorn
tensor[1]=torch.zeros_like(input=tensor[1])
print(tensor)


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([4, 5, 6])
tensor([[1, 2, 3],
        [0, 0, 0]])


dtype concept and by default data type in the pytorch is float_32

### tensor data types issue
tensor datatype  is one of the 3 big errors you will run in to with pytorch and deeplearning:
1. tensors not right data type
2. tensor not right shape
3. tensor not on right device

In [79]:
float_32_tensor=torch.tensor([2.0,3.0,4.0],
                             dtype=None,
                             device=None, # on which device is your tensor on
                             requires_grad=False # whether or not to track gradients with this tensors operations
                             )

In [80]:
# changing the data type
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([2., 3., 4.], dtype=torch.float16)

In [81]:
float_32_tensor*float_32_tensor

tensor([ 4.,  9., 16.])

In [83]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [84]:
float_32_tensor*int_32_tensor

tensor([ 6., 18., 36.])

getting the tensor information

In [85]:
some_tensor=torch.rand(3,4)
print(some_tensor)
print(f"data type of tensor:{some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"device of tensor:{some_tensor.device}")


tensor([[0.3317, 0.6434, 0.6521, 0.3158],
        [0.6727, 0.2304, 0.2871, 0.4306],
        [0.8024, 0.8319, 0.2590, 0.5087]])
data type of tensor:torch.float32
shape of tensor:torch.Size([3, 4])
device of tensor:cpu


####manipulating the tensor (tensor operation)
addition
multiplication  (element wise)
substraction
division
matrix-multiplication

In [16]:
# create
import torch
import numpy as np
import pandas as pd

tensor=torch.tensor([1,2,3])
# the main thing it only make changes one time and not make change in the original one
print(tensor+10)
print(tensor+100)
print(tensor+10)

tensor([11, 12, 13])
tensor([101, 102, 103])
tensor([11, 12, 13])


In [10]:
# sub
tensor=torch.tensor([1,2,3])
print(tensor-10)


tensor([-9, -8, -7])


In [12]:
# builtin functions
tensor=torch.tensor([1,2,3])
print(torch.mul(tensor,10))
print(torch.add(tensor,10))
print(torch.sub(tensor,10))
print(torch.div(tensor,2))

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([0.5000, 1.0000, 1.5000])


### matrix multiplication in the pytorch
basic main rule in that:

the number of column of 1 matrix will be equal to the number of rows of the 2 matrix
and the number of rows of 1 matrix will be equall to the number of the columns of the 2 matrix

1. the inner dimension must match for multiplication
2. the resulting matrix has shape of the out dimension like
(2,3)@(3,2) -> (2,2)


(3,2)@(2,3)-> (3,3)

And two main way:
element wise multi
matrix multiplication (dot_product)

link:
http://matrixmultiplication.xyz/

In [21]:
tensor
# its element wise
print(tensor ,"*",tensor)
print(tensor*tensor)
# its dot pord
print(torch.matmul(tensor,tensor))

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])
tensor(14)


the error most time occure ont he base of the shape

In [28]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
# it not match the rule one inner dimension not matches perfectly
#torch.matmul(tensor_A, tensor_B)
# take the method called transpose here
tensor_B_t=tensor_B.T
tensor_B_t.shape
print("multiplication done here after the trnaspose ",torch.matmul(tensor_A,tensor_B_t))

multiplication done here after the trnaspose  tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


### Finding the max,min,means,sum (tensor aggregation)

mean not work on the long data type

In [32]:
print(tensor.min())
print(tensor.max())


tensor(1)
tensor(3)


In [34]:
# it not work on the long data type
tensor.type(torch.float32).mean()
print(tensor.sum())

tensor(6)


arg use with min ,max to find the index of the max value and the min value

In [49]:
print(tensor.argmin())
print(tensor.argmax())
tensor=torch.tensor([1,2,3,4,5,7,6,9,8])
# it gives the indices after teh sorting not the exact values after sorting means according to original one 7 is at 5 index and 6 at six si it swap it after sorting and after that give index list that index 6 goes to 5 place and 5 goes to 6 place
print(tensor.argsort())


tensor(0)
tensor(7)
tensor([0, 1, 2, 3, 4, 6, 5, 8, 7])


In [51]:
# but it gives the sorted list
values=tensor.sort()
print(values)

torch.return_types.sort(
values=tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
indices=tensor([0, 1, 2, 3, 4, 6, 5, 8, 7]))


### reshaping ,stacking ,squeezing ,unsqueezing  tensors
1. torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
2. Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
3. torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
4. torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.
5. torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.
6. torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims.

| Operation | What it does                         | Common use                                  |
| --------- | ------------------------------------ | ------------------------------------------- |
| reshape   | Changes shape safely                 | Flattening, refactoring tensor shape        |
| view      | Changes shape fast, needs contiguity | Simple reshaping when memory layout is fine |
| squeeze   | Removes size-1 dimensions            | Remove extra batch/channel dim              |
| unsqueeze | Adds size-1 dimensions               | Add batch dimension                         |
| permute   | Reorders axes                        | Image/video tensor format changes           |

In [62]:
x=torch.arange(1.,9.)
x
print(x.shape)

torch.Size([8])


In [71]:
# the main thing that remain in mind is that shape will be according to original tesnor dim
x_reshaped=x.reshape(1,8)
print(x_reshaped)
print(x_reshaped.shape)
# like here original one has has 8 shape and so reshape 2,4 also=8 same  or 1*8 =8 same
x_reshape=x.reshape(2,4)
print(x_reshape)
print(x_reshape.shape)
p

tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
torch.Size([1, 8])
tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4])
2
2
1


In [74]:
# view (keep same data as original but changes view )
z=x.view(1,8)
print(z)
print(z.shape)

# changing the view also make changes in the original  let see
z[:,0]=4
z,x

tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
torch.Size([1, 8])


(tensor([[4., 2., 3., 4., 5., 6., 7., 8.]]),
 tensor([4., 2., 3., 4., 5., 6., 7., 8.]))

In [80]:
# stacking tensor on top of each other
# but the thing that remain in mind is that dim remain same never get change remain same as compared to original one
x_stacked=torch.stack([x,x,x,x],dim=1)
print(x_stacked)

print(x_stacked.shape)

tensor([[4., 4., 4., 4.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.]])
torch.Size([8, 4])


In [98]:
# squeezing means removing the dimension from tensor
x_org=torch.arange(1,9)
print(x_org)
print(x_org.shape)

x_reshaped=x_org.reshape(1,8)
print(x_reshaped)
print(x_reshaped.shape)

# now squeez that tensor
x_squeezed=x_reshaped.squeeze()
print(x_squeezed)
print("shape aftert the squeez",x_squeezed.shape)


#unsqeez means adding the dimension in to tensor
x_unsqueezed=x_squeezed.unsqueeze(dim=1)
print(x_unsqueezed)
print("shape before the squeez",x_squeezed.shape,"shape after the squeez",x_unsqueezed.shape)



tensor([1, 2, 3, 4, 5, 6, 7, 8])
torch.Size([8])
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])
torch.Size([1, 8])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
shape aftert the squeez torch.Size([8])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])
shape before the squeez torch.Size([8]) shape after the squeez torch.Size([8, 1])


In [103]:
# permute it does not chnage the shape number wise ,it changes the axis wise
pic_tensor=torch.rand(size=(224,224,3)) # like height,width,colour-side
per_pic=pic_tensor.permute(2,0,1)# now colour-side,height,width
print("shape before the permute",pic_tensor.shape)
print("shape after the permute",per_pic.shape)

shape before the permute torch.Size([224, 224, 3])
shape after the permute torch.Size([3, 224, 224])


In [111]:
print("values of original",pic_tensor[0,0,0])
print("values of permute",per_pic[0,0,0])
print("before change",pic_tensor[0,0,0])
pic_tensor[0,0,0]=1.222
print("after changing the values in the  original",pic_tensor[0,0,0]," also cause change in the permute",per_pic[0,0,0])


values of original tensor(1.2220)
values of permute tensor(1.2220)
before change tensor(1.2220)
after changing the values in the  original tensor(1.2220)  also cause change in the permute tensor(1.2220)


indexing ans slicing in the tensor same like the numpy

In [114]:
tensor=torch.rand(1,9).reshape(1,3,3)
tensor

tensor([[[0.6552, 0.5817, 0.8360],
         [0.1079, 0.3657, 0.9342],
         [0.5341, 0.5572, 0.8179]]])

In [116]:
tensor[0]

tensor([[0.6552, 0.5817, 0.8360],
        [0.1079, 0.3657, 0.9342],
        [0.5341, 0.5572, 0.8179]])

In [117]:
tensor[0][0]

tensor([0.6552, 0.5817, 0.8360])

In [118]:
tensor[0][0][0]   # first dimension first rown first element

tensor(0.6552)

In [119]:
tensor[0][2][2]

tensor(0.8179)

In [126]:
print(tensor[:,0])
print(tensor[0,:])

tensor([[0.6552, 0.5817, 0.8360]])
tensor([[0.6552, 0.5817, 0.8360],
        [0.1079, 0.3657, 0.9342],
        [0.5341, 0.5572, 0.8179]])


In [127]:
tensor[:,:,1]

tensor([[0.5817, 0.3657, 0.5572]])

In [128]:
tensor[:,1,:]

tensor([[0.1079, 0.3657, 0.9342]])

In [129]:
tensor[:,1,1]

tensor([0.3657])

pytorch tensors and numpy
numply is popular scientigic python numerical computing library and bcz of pytorch it has functionality to interact with it.

1. data in numpy want in pytorch tensor -> torch.from_numpy()
2. pytorch tensor -> numpy -> torch.tensor.numpy()

In [5]:
# numpy array to tensor
import torch
import numpy as np
array=np.arange(1.0,8.0)
print(array,"also the type",array.dtype)
# converting them in to tensor
tensor=torch.from_numpy(array)# when converting numpy to tensor  -> pytorch reflect numpy by default data type of float 64 unless specified otherwise
print(tensor,"also the type",tensor.dtype)

[1. 2. 3. 4. 5. 6. 7.] also the type float64
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64) also the type torch.float64


In [9]:
#change the vlaue of the array and what effect on the tensor ?
array=array+1 # so keep in mind keep change in the array never causes the change in the tensor
array,tensor

(array([ 4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [12]:
# tensor to numpy array
tensor=torch.ones(7)
numpy=tensor.numpy()# same numpy taking the by deafualt data type of the tensor
tensor,numpy

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [14]:
# same changing in the value of the tensor never cause the change in the numpy
tensor=tensor+1
tensor,numpy

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducibility means you intentionally control randomness so the same code can produce the same random tensors, the same initialization, and the same training behavior again

In [16]:
tensor_A=torch.rand(3,4)
tensor_B=torch.rand(3,4)
print(tensor_A)
print(tensor_B)
# generates the diff random number
print(tensor_A==tensor_B)

tensor([[0.0241, 0.9326, 0.0465, 0.9537],
        [0.1990, 0.6178, 0.0350, 0.7721],
        [0.6501, 0.5650, 0.8481, 0.9545]])
tensor([[0.5810, 0.1841, 0.1337, 0.4207],
        [0.2954, 0.1514, 0.7981, 0.8895],
        [0.9045, 0.6679, 0.3085, 0.8051]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [26]:
# let make the some reproducible tensor
import torch

# set the random value
random_seed=42
torch.manual_seed(random_seed)
tensor_C=torch.rand(3,4)
# if yu creating the random seed one after one other so every time we had to caal teh torch.manual_seed()
torch.manual_seed(random_seed)
tensor_D=torch.rand(3,4)
print(tensor_C)
print(tensor_D)
print(tensor_C==tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
