<a href="https://colab.research.google.com/github/saim9211/DeepLearning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### resource to follow  : https://www.learnpytorch.io/00_pytorch_fundamentals/


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import torch
print(torch.__version__)

2.11.0+cpu


### introduction to tensor in detial

In [2]:
scalar=torch.tensor(6)
scalar

tensor(6)

In [3]:
scalar.ndim

0

In [9]:
# getting back the tensor as number
scalar.item()

6

In [31]:
# vector number
vec=torch.tensor([4,3])

In [32]:
# vector dimension
# trick count the number of square brackets outside of one side

vec.ndim

1

In [33]:
# tell about the element inside and  the outside
vec.shape

torch.Size([2])

In [17]:
# matrix
matrix=torch.tensor([[1,2,3],[4,5,6]])
print(matrix.ndim)
#number of row and column
print(matrix.shape)
print(matrix[1])

2
torch.Size([2, 3])
tensor([4, 5, 6])


In [25]:
# practice

matrix=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


#### for random tensor creation bcz most of the machine learning used the random tensor  first creat the random tensor and then according to data update it optimize them
start with the random number -> look at the data-> update the random tensor -> look at the data -> update random tensor


In [38]:
ran_Tensor=torch.rand(3,4)
print(ran_Tensor)
print(ran_Tensor.ndim)
print(ran_Tensor.shape)
# to get the type of the tensor
print(ran_Tensor.dtype)

tensor([[0.5693, 0.8597, 0.8858, 0.2331],
        [0.3694, 0.5481, 0.8424, 0.2083],
        [0.2155, 0.0934, 0.7012, 0.0491]])
2
torch.Size([3, 4])
torch.float32


In [59]:
# it can adjust the size to be whatever we want
# it means 4 rows and 4 column 2 dimesional one matrix
torch.random=torch.rand(size=(4,4))
# it means 4 sample of 4 rows and 2 column
torch.random=torch.rand(size=(4,4,2))
# it means 2  sample(  (4sample(4,2))
# (2 batch size  (((4 channel  (4 rows,2  column))))
random_tensor=torch.rand(size=(2,4,4,2))
print(random_tensor.shape)
print("dimension:",random_tensor.ndim)
print(random_tensor)

torch.Size([2, 4, 4, 2])
dimension: 4
tensor([[[[0.0671, 0.5664],
          [0.3048, 0.8619],
          [0.4842, 0.7972],
          [0.3956, 0.7203]],

         [[0.6811, 0.2032],
          [0.4973, 0.7171],
          [0.3267, 0.9850],
          [0.9980, 0.9958]],

         [[0.4840, 0.4159],
          [0.9415, 0.1100],
          [0.7320, 0.1540],
          [0.2941, 0.8074]],

         [[0.4260, 0.6533],
          [0.1962, 0.0359],
          [0.2623, 0.9599],
          [0.2573, 0.8376]]],


        [[[0.5302, 0.0709],
          [0.7398, 0.0174],
          [0.8214, 0.8608],
          [0.6643, 0.4417]],

         [[0.4637, 0.4280],
          [0.0061, 0.4753],
          [0.1048, 0.9214],
          [0.0023, 0.2402]],

         [[0.5913, 0.8704],
          [0.4764, 0.0920],
          [0.2580, 0.2977],
          [0.1257, 0.7874]],

         [[0.3534, 0.0535],
          [0.8102, 0.7902],
          [0.1044, 0.8073],
          [0.5503, 0.1668]]]])


Zeros  and ones

In [63]:
# create the tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [64]:
# create the ones tensor
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

concept of the range

In [70]:
# it work like the same like numpy np.arange
print(torch.arange(1,10))
# start ,end, then steps in them
print(torch.arange(start=0,end=1000,step=100))


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])


In [76]:
one_to_fiver=torch.arange(start=1,end=6,step=1)
print(one_to_fiver)
# make the use of the _like method to make it change like other
zero_one_fiver=torch.zeros_like(input=one_to_fiver)
print(zero_one_fiver)
one=torch.ones_like(input=one_to_fiver)
print(one)

tensor([1, 2, 3, 4, 5])
tensor([0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1])


In [102]:
tensor=torch.tensor([[1,2,3],[4,5,6]])
print(tensor)
print(tensor[1])
# for changing the certain vector in the tensorn
tensor[1]=torch.zeros_like(input=tensor[1])
print(tensor)


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([4, 5, 6])
tensor([[1, 2, 3],
        [0, 0, 0]])


dtype concept and by default data type in the pytorch is float_32

### tensor data types issue
tensor datatype  is one of the 3 big errors you will run in to with pytorch and deeplearning:
1. tensors not right data type
2. tensor not right shape
3. tensor not on right device

In [79]:
float_32_tensor=torch.tensor([2.0,3.0,4.0],
                             dtype=None,
                             device=None, # on which device is your tensor on
                             requires_grad=False # whether or not to track gradients with this tensors operations
                             )

In [80]:
# changing the data type
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([2., 3., 4.], dtype=torch.float16)

In [81]:
float_32_tensor*float_32_tensor

tensor([ 4.,  9., 16.])

In [83]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [84]:
float_32_tensor*int_32_tensor

tensor([ 6., 18., 36.])

getting the tensor information

In [85]:
some_tensor=torch.rand(3,4)
print(some_tensor)
print(f"data type of tensor:{some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"device of tensor:{some_tensor.device}")


tensor([[0.3317, 0.6434, 0.6521, 0.3158],
        [0.6727, 0.2304, 0.2871, 0.4306],
        [0.8024, 0.8319, 0.2590, 0.5087]])
data type of tensor:torch.float32
shape of tensor:torch.Size([3, 4])
device of tensor:cpu


####manipulating the tensor (tensor operation)
addition
multiplication  (element wise)
substraction
division
matrix-multiplication

In [16]:
# create
import torch
import numpy as np
import pandas as pd

tensor=torch.tensor([1,2,3])
# the main thing it only make changes one time and not make change in the original one
print(tensor+10)
print(tensor+100)
print(tensor+10)

tensor([11, 12, 13])
tensor([101, 102, 103])
tensor([11, 12, 13])


In [10]:
# sub
tensor=torch.tensor([1,2,3])
print(tensor-10)


tensor([-9, -8, -7])


In [12]:
# builtin functions
tensor=torch.tensor([1,2,3])
print(torch.mul(tensor,10))
print(torch.add(tensor,10))
print(torch.sub(tensor,10))
print(torch.div(tensor,2))

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([0.5000, 1.0000, 1.5000])


### matrix multiplication in the pytorch
basic main rule in that:

the number of column of 1 matrix will be equal to the number of rows of the 2 matrix
and the number of rows of 1 matrix will be equall to the number of the columns of the 2 matrix

1. the inner dimension must match for multiplication
2. the resulting matrix has shape of the out dimension like
(2,3)@(3,2) -> (2,2)


(3,2)@(2,3)-> (3,3)

And two main way:
element wise multi
matrix multiplication (dot_product)

link:
http://matrixmultiplication.xyz/

In [21]:
tensor
# its element wise
print(tensor ,"*",tensor)
print(tensor*tensor)
# its dot pord
print(torch.matmul(tensor,tensor))

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])
tensor(14)


the error most time occure ont he base of the shape

In [28]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
# it not match the rule one inner dimension not matches perfectly
#torch.matmul(tensor_A, tensor_B)
# take the method called transpose here
tensor_B_t=tensor_B.T
tensor_B_t.shape
print("multiplication done here after the trnaspose ",torch.matmul(tensor_A,tensor_B_t))

multiplication done here after the trnaspose  tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
