In [2]:
import numpy as np 
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a[:, 1]

array([2, 5, 8])

In [8]:
a[1,:]

array([4, 5, 6])

In [9]:
a[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [13]:
a[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [14]:
a[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [15]:
a[-1]

array([7, 8, 9])

In [16]:
a[1:,2:]

array([[6],
       [9]])

In [ ]:
a[1:3, 2:4]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed